# rm the outdated image: docker rmi qingfengxia/ppp-fedora
# Remove all untagged images: docker rmi $(docker images | grep "^<none>" | awk "{print $3}")
# command to build: docker build  --rm -f Dockerfile_fedora  -t qingfengxia/ppp-fedora .
#
# to test this image:
#         git clone this project, optionally, rename it to `ppp`
#         change directory to the `ppp` repo toplevel, if build folder exists, `sudo rm -rf build && mkdir build`
#         docker run -ti  -w /project/build/  -v $(pwd):/project/  qingfengxia/ppp-fedora bash
# before build inside docker container: git submodule update --init --recursive
#
# build package and test after install
# 
# release this image
# to rename/tag the image by `docker tags` if not yet done
# docker login && docker push qingfengxia/ppp-fedora:latest

# fedora30 has default python as python3, and opencascade 7.4 and freecad rpm

# Base OS layer: should works for federa 30+
FROM fedora:latest

LABEL name="ppp-fedora" \
    maintainer="qingfeng.xia @ UKAEA" \
    version="0.3" \
    description="federa with FreeCAD python3 and opencascade 7.4 for parallel preprocessor development CI"

# must be root user to use GITHUB_WORKSPACE
#USER root

# avoid interactive timezone selection, ENV setting will affect child image
# ENV TZ=Europe/London
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# you must update before any yum install or add a repo
# `dnf-cli` is needed to to add copr repo
RUN yum install copr-cli -y && yum update -y 

# g++ 9.2 for f30 high enough, there is no need to install boost-devel
RUN yum install g++ cmake make git doxygen nano openmpi-devel eigen3-devel boost-devel rpm-build -y

# export path for openmpi: export PATH=/usr/lib/openmpi/bin/ && mpicc -v

# for OpenCASCADE,  need openGL, xwindows, 
# python3 and qt5 devel for parallel preproessor
# package name distinguish captical letter, while debian name is just  libxmu
RUN yum install tk tcl tk-devel tcl-devel tbb tbb-devel freetype freetype-devel freeimage freeimage-devel  \
       glew-devel SDL2-devel SDL2_image-devel glm-devel libXmu-devel libXi-devel \
       python3 python3-devel  -y

# optional dep
#RUN yum install qt5-devel qt5-qtwebsockets-devel qt5-qtwebsockets -y

# Since Jan 2020, opencascade 7.4 package  for fedroa 30+ is available, 
# freecad 0.18.4 stable(python3 occt 7.4 is available in official repo too.
RUN dnf install opencascade-foundation  opencascade-modeling opencascade-ocaf \
    opencascade-visualization opencascade-devel opencascade-draw -y

# install FreeCAD 0.18 stable from official repo, or older version dep on fedora version
# RUN yum install freecad -y
# or install the daily build of freecad
# RUN yum install dnf-plugins-core -y && dnf copr enable @freecad/nightly  -y && yum install freecad -y


# Copies your code file from your action repository to the filesystem path `/` of the container
COPY scripts/build_package.sh /build_package.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/build_package.sh"]



